name: Build and Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get build dependencies
        run: |
          sudo apt-get install cmake ninja-build
      
      - name: Build
        run: |
          cmake . -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DBITRAY_BUILD_TESTS=ON
          cmake --build build

      - name: Run simple ByteRay tests
        run: |
          ./build/tests/unit/test_simplebyteray